<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.openjtrace</groupId>
        <artifactId>openjtrace-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>cli</artifactId>

    <dependencies>
        <!-- Parser and Analyzers -->
        <dependency>
            <groupId>org.openjtrace</groupId>
            <artifactId>graph-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjtrace</groupId>
            <artifactId>parser-maven</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjtrace</groupId>
            <artifactId>parser-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjtrace</groupId>
            <artifactId>analyzer-http</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjtrace</groupId>
            <artifactId>analyzer-dubbo</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjtrace</groupId>
            <artifactId>analyzer-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjtrace</groupId>
            <artifactId>analyzer-mq</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjtrace</groupId>
            <artifactId>analyzer-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjtrace</groupId>
            <artifactId>analyzer-mongodb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjtrace</groupId>
            <artifactId>report-html</artifactId>
        </dependency>

        <!-- Command Line Parser -->
        <dependency>
            <groupId>com.beust</groupId>
            <artifactId>jcommander</artifactId>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.openjtrace.cli.OpenJTraceCli</mainClass>
                                </transformer>
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
